apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: source
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_HOST
          value: "postgres"
        - name: KAFKA_HOST
          value: "kafka:9092"
        - name: POSTGRES_DB
          value: "sh_db"
        - name: POSTGRES_USER
          value: "sh"
        - name: POSTGRES_PASSWORD
          value: "sh123"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: source
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432